# Generated by Django 4.2.7 on 2023-11-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_task_created_time_task_completed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
